### ISSUE TITLE
Does not work on personal private repos due to "Draft" hub create release option

### ISSUE THREAD

**Issue by shanejonas** [MetaMask/action-create-release-pr#67]
Using this on private personal repos errors:

`pull request create failed: GraphQL error: Draft pull requests are not supported in this repository.`

Their docs describe:

> Draft pull requests are available in public repositories with GitHub Free for organizations and legacy per-repository billing plans, and in public and private repositories with GitHub Team, GitHub Enterprise Server 2.17+, and GitHub Enterprise Cloud

> Source: https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests#draft-pull-requests

Ideally this `--draft` should become optional via an input parameter

https://github.com/MetaMask/action-create-release-pr/blob/34e157f62710becd1594ab5de5e4a78238a5bc0d/scripts/create-release-pr.sh#L38

**Comment by Gudahtt** [comment]
This appears to be resolved in #76
