### ISSUE TITLE
Fix monorepo version synchronization behavior

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/action-create-release-pr#79]
Currently, this action "synchronizes" package versions in monorepos (i.e., updates the version of all monorepo packages wherever they appear as dependencies in this monorepo), for major releases only. This has often created problems for us, and we should consider making it always synchronize package versions or parameterize the behavior.

We need to keep two things in mind while making this change:
1. The most recent _published_ versions of all packages should be compatible per SemVer
2. Packages should always be internally compatible in the monorepo
    - This is the rub, because if package versions become unsynchronized in the monorepo, `yarn setup`/ `yarn install` will install monorepo packages from the registry instead of linking the local versions. IIRC, there's some kind of setting (maybe in `.yarnrc`?) that forces `yarn` to always install from the monorepo, but I'm not sure. If that setting exists, we could just document that monorepos that use this action should enable it. Otherwise, we may just have to default to synchronizing versions.

**Comment by mcmire** [comment]
In our group meeting a few weeks ago, we agreed that the original motivation behind this issue (as explained in the PR) is no longer relevant. Technically point 2 is something we still want to do, but it's something that is handled by switching to Yarn v3 (which is already done for both `controllers` and `snaps-skunkworks`) and using `workspace:~` to keep versions synchronized internally within the monorepo (which is something we plan on doing for `controllers` and we _may_ want to do for `snaps-skunkworks` if that is needed). Also, we plan on replacing this action with a command-line tool that will get run locally. Bottom line: This is obsolete, and we should re-evaluate this once we complete converting `controllers` into a monorepo.
