### ISSUE TITLE
Develop command-line tool based on this action

### ISSUE THREAD

**Issue by mcmire** [MetaMask/action-create-release-pr#93]
Currently, this action makes a set of changes that are needed to create a new release and groups those changes into a branch/PR. For convenience we call these changes a "release candidate", and in order to create a release candidate, two things must happen:

1. The root package should be bumped along with any packages that have changed since the previous release.
2. The changelog should be updated with the commits that will be included in the new release.

We want to change the process of releasing a monorepo such that:

1. When bumping packages, versions are no longer synchronized with the root package.
2. Each package gets its own changelog, so each package's changelog should be updated accordingly.

To accommodate this, we want to turn this action into a command-line tool. This tool should work for both monorepos and polyrepos. This likely means we need to create a new repo to hold this tool, but I am creating this issue here for convenience.

## Monorepos

For a particular monorepo, when the developer runs this tool, it should list all packages matched by the root package's `workspaces` property that have been updated since the last tag of the monorepo. This prompt should allow the developer to select which packages should be bumped and how (major, minor, patch, exact version).

For each package the developer has selected, the tool should then look at the commits made since the last published release of the package that change any part of the package and add those commits under a new section within the package's changelog that is headered by the new version selected for that package.

## Polyrepos

The command-line tool should also work for polyrepos as well. In this case, there is no need to list multiple packages; all that is required is to ask for how the root package should be bumped (major, minor, patch, exact version).

The tool should then look at the commits made since the last published release of the package and add those commits under a new section within the package's changelog that is headered by the new version selected for that package.

**Comment by Gudahtt** [comment]
The CLI tool `create-release-branch` has been created to serve this purpose.
